### PR TITLE
Regaccess register size

### PR DESCRIPTION
**Pull request by koenenwmn**
@imphil , @wallento , please have a look and see if you agree.

### CODE REVIEW

**Comment by imphil** [comment]
Looks good! Did you also create a test_osd_regaccess, or is this something to add for later?

**Comment by koenenwmn** [comment]
So far I did not. I did, however, quickly test a 32, 64, and 128-bit read access to the base registers using the base registers test of the STM module.

**Comment by imphil** [comment]
Please add a cocotb test for the osd_regaccess functionality. It should especially cover the reads and writes of all register sizes when forwarded to an external module (i.e. the "non base registers"). Also interesting are the error case, i.e. if the register size doesn't match expectations.

**Comment by koenenwmn** [comment]
Added a cocotb test. The module should be working.

**Comment by imphil** [comment]
Looks good, thanks @koenenwmn !

**Pull request merged**
