### PR TITLE
DEM-UART: Fixed event_dest not being used as the event destination.

### PR DESCRIPTION
**Pull request by ThomasLeyk**

### CODE REVIEW

**Comment by imphil** [comment]
Please rebase this commit on top of the current osd-next branch (use a git fetch first). This should reduce the commits to just the last one with your change.

**Comment by imphil** [comment]
Additionally, please have a commit message starting with "DEM UART: " to quickly indicate what area of the code the commit relates to.

**Comment by ThomasLeyk** [comment]
I ran 'git fetch' followed by a 'git rebase osd-next' and then resolved the merge conflicts during the rebase. But it looks like the PR is still containing all 3 commits just like before.

**Comment by imphil** [comment]
Your local osd-next branch is not up-to-date with origin/osd-next. Two options:

~~~
git checkout osd-next
git pull
git checkout uart-dem
git rebase osd-next
~~~

or (recommended)

~~~
git checkout uart-dem
git rebase origin/osd-next
~~~

**Pull request merged**
